### ISSUE TITLE
Suggestion: create a GitHub release after pushing each tag

### ISSUE THREAD

**Issue by aantron** [libuv/libuv-release-tool#12]
This allows GitHub to notify GitHub users of releases, if they are watching the repo for *Releases only* (at least, as I understand it).

The release text can be empty. Another easy option is to paste in the tag message.

My apologies if this has been suggested in the past; I searched only this repo.

**Comment by cjihrig** [comment]
I've moved this issue to the libuv-release-tool repo, as any changes to the release process would need to happen here.

**Comment by richardlau** [comment]
> 
> 
> I've moved this issue to the libuv-release-tool repo, as any changes to the release process would need to happen here.

This issue could probably be solved now with GitHub Actions and the [create-release action](https://github.com/actions/create-release).

**Comment by aantron** [comment]
I'd welcome that. I recently released the [binding](https://github.com/aantron/luv) I was working on. My current way of checking for libuv releases is to manually poll the release page weekly. That's not difficult, but it would be nice to simply get an email, like sent by many other projects I monitor.

**Comment by aantron** [comment]
Note that the *binding* is creating [proper releases](https://github.com/aantron/luv/releases).

**Comment by aantron** [comment]
After the latest GitHub redesign, this is what is shown in the "releases" section on the main page of a [project](https://github.com/aantron/luv) that does releases:

![luv-releases](https://user-images.githubusercontent.com/12073668/100194665-2495b680-2f07-11eb-805a-cbf7ebc99079.PNG)

<br/>

This is what is shown on [libuv's page](https://github.com/libuv/libuv), because it does not do releases:

![libuv-tags](https://user-images.githubusercontent.com/12073668/100194734-47c06600-2f07-11eb-90b7-bb881cc0e583.PNG)

<br/>

As before, because libuv does not do releases, it is still **not** possible to use GitHub's support for receiving emails about libuv releases. This does nothing for libuv:

![watch](https://user-images.githubusercontent.com/12073668/100195096-e4830380-2f07-11eb-885b-2b7080a773b7.PNG)

<br/>

By comparison, as one concrete example, I monitor the releases of [Dune](https://github.com/ocaml/dune), a build system I use for the first project I linked. You can see its [releases page](https://github.com/ocaml/dune/releases) with neat, hyperlinked release objects. I receive an email-rendered version of these upon each release. You can also see Dune's latest release info at a glance on its main page.

![dune-release](https://user-images.githubusercontent.com/12073668/100195500-78ed6600-2f08-11eb-8985-fd68f4685d3e.PNG)

<br/>

I also monitor releases of [Windows Terminal](https://github.com/Microsoft/Terminal), which I use with WSL. Windows Terminal is a very popular project that uses GitHub releases to communicate with its users.

To mention myself, I use GitHub releases in all my user-facing repos. When GitHub itself added support for receiving emails on releases only, we were able to [retire](https://github.com/ocsigen/lwt/issues/309#issuecomment-443124784) an [announcements issue](https://github.com/ocsigen/lwt/issues/309) in a major OCaml project I was maintaining at the time.

<br/>

There are very many other examples. I argue the above points show that creating release objects is the intended way to use GitHub.

At minimum, I think you could simply (automatically?) paste the tag texts from your current practice into release objects. They won't be so neatly hyperlinked as for the projects I linked, but they are already formatted as Markdown lists, and that will at least trigger email notifications. The two lines at the top of each tag's text will already be interpreted correctly as two separate lines by GitHub-flavored Markdown. I suggest doing this starting from the next tag, so as not to trigger notifications at this point for older releases.

And I'd like to request properly that libuv start making release objects on GitHub :)

**Comment by aantron** [comment]
Great, many thanks! I got the email notification!

**Comment by aantron** [comment]
Only recommendation wowuld be to paste the changelog into the release text; however, I already know where to find it, so it's fine for me not to May be helpful for other people watching.
