### ISSUE TITLE
Add support for REPLACEME

### ISSUE THREAD

**Issue by cjihrig** [libuv/libuv-release-tool#7]
By adding a REPLACEME feature (such as what [Node.js](https://github.com/nodejs/node/blob/master/doc/releases.md#step-3-update-any-replaceme-tags-in-the-docs) does), it removes the need to guess what version something will first appear in when landing a PR. See https://github.com/libuv/libuv/pull/1060#issuecomment-253209525.

**Comment by saghul** [comment]
Agreed! You just volunteered, right? 😄 

FWIW we should also change the RTD hook config so the documentation is only regenerated when a tag is pushed, not with every commit as it happens now.

**Comment by vtjnash** [comment]
https://github.com/nodejs/node/blob/master/doc/guides/releases.md#step-3-update-any-replaceme-and-dep00xx-tags-in-the-docs
